exclude-newer = "7 days"
constraint-dependencies = [
    "mistralai!=2.4.6",
    "guardrails-ai!=0.10.1",
]

[exclude-newer-package]
breakout-turbo-env = "2026-07-23T11:27:02Z"
stable-retro-turbo = "2026-07-22T17:30:25Z"
supermariobrosnes-turbo = "2026-07-23T11:52:37Z"
