exclude-newer = "7 days"
constraint-dependencies = [
    "mistralai!=2.4.6",
    "guardrails-ai!=0.10.1",
]

[exclude-newer-package]
breakout-turbo-env = "2026-07-21T07:46:16.759348Z"
stable-retro-turbo = "2026-07-20T15:21:26.271359Z"
supermariobrosnes-turbo = "2026-07-21T07:12:44.073250Z"
