exclude-newer = "7 days"
constraint-dependencies = [
    "mistralai!=2.4.6",
    "guardrails-ai!=0.10.1",
]

[exclude-newer-package]
breakout-turbo-env = "2026-07-21T07:46:17Z"
stable-retro-turbo = "2026-07-20T15:21:27Z"
supermariobrosnes-turbo = "2026-07-22T10:23:49Z"
